# thanks to iggyvolz for the config file for pushing travis builds!

language: csharp
solution: AnimmexAPI.sln

after_success:
  - shopt -s extglob
  - mv /bin/Release/AnimmexAPI.dll AnimmexAPI.dll
  - mv /bin/Release/ModernHttpClient.dll ModernHttpClient.dll
  - rm !(AnimmexAPI.dll ModernHttpClient.dll)
  - git clone https://github.com/kade-robertson/AnimmexAPI.git
  - SHA=`git rev-parse --verify HEAD`
  - git checkout --orphan gh-pages
  - git pull origin gh-pages
  - git status
  - if [[ -z `git diff --exit-code` ]]; then echo "No changes to the output on this push; exiting."; exit 0; fi
  - git config user.name "Travis CI"
  - git config user.email "travis_build_key@example.com"
  - rm master-build.zip
  - zip master-build.zip AnimmexAPI.dll ModernHttpClient.dll
  - git add -f master-build.zip
  - git commit -m "deploy to GitHub Pages $SHA"
  - ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
  - ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
  - ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
  - ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git push $SSH_REPO gh-pages

env:
  global:
  - ENCRYPTION_LABEL: "37e98f6522e8"
  - COMMIT_AUTHOR_EMAIL: "travis_build_key@example.com"
  